import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  globalMargins: {
    backgroundColor: '#fff',
    flex: 1,
  },
  titulo: {
    color: 'black',
    fontSize: 30,
    textAlign: 'center',
    top: 30,
    fontFamily: 'Cochin',
  },
  logo: {
    borderRadius: 1,
    width: 60,
    height: 60,
    alignSelf: 'center',
    top: 5,
  },

  moneda: {
    borderRadius: 1,
    width: 60,
    height: 60,
    alignSelf: 'center',
    top: 20,
  },
  imagen1: {
    width: 180,
    height: 180,
    borderRadius: 10,
    margin: 8,
    borderColor: '#960018',
    borderWidth: 5,
  },
  imagen2: {
    width: 180,
    height: 180,
    borderRadius: 10,
    margin: 8,
    borderColor: '#960018',
    borderWidth: 5,
  },
  imagen3: {
    width: 180,
    height: 180,
    borderRadius: 10,
    alignContent: 'space-between',
    margin: 8,
    borderColor: '#960018',
    borderWidth: 5,
  },

  imagen4: {
    width: 180,
    height: 180,
    borderRadius: 10,
    alignContent: 'space-between',
    margin: 8,
    borderColor: '#960018',
    borderWidth: 5,
  },

  imagen5: {
    width: 380,
    height: 380,
    alignSelf: 'center',
  },

  v1: {
    flexDirection: 'row',
    alignContent: 'center',
    top: 80,
  },
  v2: {
    flexDirection: 'row',
    top: 90,
  },

  palabra: {
    color: '#ff8478',
    top: 150,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  frase: {
    top: 10,
    color: '#ff8478',
    textAlign: 'center',
    fontSize: 30,
  },
  frases: {
    color: '#ff8478',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 30,
    fontFamily: 'lucida grande',
  },
  copy: {
    color: '#960018',
    top: 10,
    textAlign: 'center',
  },
  titulos: {
    color: 'black',
    fontSize: 30,
    textAlign: 'center',
    alignSelf: 'center',
    top: 80,
    fontFamily: 'Cochin',
  },
  imagen: {
    width: 150,
    height: 150,
    borderRadius: 45,
    alignSelf: 'center',
    top: '50%',
  },
  parrafo: {
    fontSize: 15,
    textAlign: 'center',
    alignSelf: 'center',
    top: 90,
  },
  parrafo1: {
    fontSize: 16,
    top: 70,
    textDecorationLine: 'underline',
    color: '#d94032',
    left: 90,
  },
  input: {
    width: '80%',
    height: '17%',
    margin: 12,
    borderWidth: 1,
    padding: 10,
    borderColor: '#c2c2c2',
    borderBottomColor: '#d94032',
    alignSelf: 'center',
    top: 100,
  },
  btn1: {
    width: '80%',
    height: '17%',
  },
  eye: {
    left: 320,
    top: 45,
    color: '#d94032',
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#d94032',
    padding: 10,
    width: '35%',
    alignSelf: 'center',
    borderRadius: 8,
  },
  btntxt: {
    color: 'white',
  },
  googles: {
    width: 20,
    height: 20,
  },
  button1: {
    borderWidth: 0.5,
    borderColor: 'gray',
    backgroundColor: 'white',
    padding: 10,
    width: '45%',
    alignSelf: 'center',
    borderRadius: 5,
    flexDirection: 'row',
  },
  title: {
    fontWeight: 'bold',
    fontSize: 30,
    padding: 24,
    textAlign: 'center',
  },
  scrollView: {flex: 1, backgroundColor: 'pink'},
  buttonLabel: {fontWeight: 'bold'},
  buttonInner: {
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonRoot: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    margin: 10,
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,

    elevation: 4,
  },
  buttonHovered: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  buttonFocused: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,
    elevation: 10,
  },
  buttonPressed: {
    backgroundColor: 'rgba(0,0,0,0.4)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.5,
    shadowRadius: 12.35,
    elevation: 19,
  },
  regis1: {
    flex: 1,
    backgroundColor: 'red',
  },
  regis2: {
    flex: 9,
    backgroundColor: 'blue',
  },
  boton:{
    width:100,
    height:30,
    backgroundColor:'#d94032',
    alignSelf:'center',
    borderColor:'#960018',
    borderWidth:2,
    borderRadius:8,
  },
  brs:{
    color:'white',
    textAlign:'center',
    top:5,
    fontSize:16,
  },
  palabrasub:{
    textDecorationLine:'underline',
    color:'#d94032',
  },
});
